# Generated by Django 2.2 on 2019-07-12 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_establecida', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_establecida', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 12, 8, 12, 33, 151641))),
            ],
        ),
    ]
